name: app_ui
description: A UI Kit for Flutter NPS module
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  lineLength: 80
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/icons/
