name: flutter_nps
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  
dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_nps
    iosBundleIdentifier: com.example.flutterNps
